const data = [
  {
    id: 1,
    level: 3,
    name: "Ohniva koule",
    dmg: "8k6",
    range: "30s",
    time: "ihned",
    focus: false,
  },
  {
    id: 2,
    level: 2,
    name: "Spatři neviditelného",
    dmg: "--",
    range: "Ty sám",
    time: "až 1h",
    focus: true,
  },
  {
    id: 3,
    level: 4,
    name: "kejkle",
    dmg: "8k8",
    range: "6s",
    time: "ihned",
    focus: false,
  },
  {
    id: 4,
    level: 4,
    name: "Hniloba",
    dmg: "8k8",
    range: "6s",
    time: "ihned",
    focus: false,
    info: "Přes tvora dle tvé volby, kterého vidíš v dosahu, se přežene vlna nekromantické energie a vysaje z jeho těla vláhu a vitalitu. Cíl si musí hodit záchranný hod na Odolnost. Když neuspěje, utrpí <strong>nekrotické zranění 8k8</strong>, nebo poloviční zranění při úspěšném záchran ném hodu. Toto kouzlo nijak nepůsobí na nemrtvé ani výtvory. <br/>  Zacílíš-li rostlinového tvora nebo magickou rostlinu, má k záchrannému hodu nevýhodu a kouzlo mu způsobí maximální zranění.    Zacílíš-li nemagickou rostlinu, která není tvor, například obyčejný strom nebo keř, tak si nehází záchranný hod; jednoduše uvadne a uhyne. Na vyšších úrovních. Sešleš-li toto kouzlo použitím pozice kouzla 5. či vyšší úrovně, za každou další úroveň pozice nad 4. se zvýší zranění o 1k8.",
  },
  {
    id: 5,
    level: 4,
    name: "Lada",
    dmg: "2k4",
    range: "6s",
    time: "ihned",
    focus: false,
  },
  {
    id: 6,
    level: 4,
    name: "poryv vetru",
    dmg: "3k8",
    range: "6s",
    time: "ihned",
    focus: false,
  },
];

export default data;
